### ISSUE TITLE
Trailing comma error with prop typing

### ISSUE THREAD

**Issue by lukasborawski** [nuxt/typescript#285] opened 2020-02-03 18:05 UTC
I'm using Typescript with Vue. I want to add typing for my props but lint giving me an error with trailing comma. In this case:

```
  21:6  error  Parsing error: Unexpected token, expected ","

   9 |       type: Object,
  10 |       required: true
> 11 |     } as PropOptions<MenuItem[]>,
     |       ^
  12 |   },
  13 |   data: () => ({}),
  14 | })
```

Code:
```
<script lang="ts">
import Vue, { PropOptions } from 'vue'
import { MenuItem } from '~/types/data'

export default Vue.extend({
  name: 'UiSubmenu',
  props: {
    submenuProp: {
      type: Object,
      required: true,
    } as PropOptions<MenuItem[]>,
  },
  data: () => ({}),
})
</script>
```

I've tried to disabled the comma-dangle rule but no results.

**Comment by kevinmarrec** [comment] 2020-02-04 13:14
@lukasborawski Is it an `eslint` error ? 

I would also advice to type it this way :
```ts
import Vue, { PropType } from 'vue'
...

submenuProp: {
  type: Array as PropType<MenuItem[]>,
  required: true
}
```

**Comment by rcheung9** [comment] 2020-02-06 08:09
Same issue.

**Comment by danielroe** [comment] 2020-02-06 08:15
Have you both followed [these instructions](https://typescript.nuxtjs.org/guide/lint.html)?

**Comment by rcheung9** [comment] 2020-02-07 00:16
@danielroe Yes, made a brand new project and created those files as specified.  Copied over a Vue file from an existing typescript Vue project and it complains.  Tried using `<MyObject>{}` and `PropOptions<MyObject>{}` and still doesn't work.

**Comment by danielroe** [comment] 2020-02-07 06:00
Would you share the repo of the new project you created? I'm not having any problems with typing/linting the Composition API.

Mind you, I type the individual type as @kevinmarrec recommended above rather than the whole prop options object.

**Comment by rcheung9** [comment] 2020-02-07 06:34
@danielroe https://github.com/rcheung9/ScanNuxt

**Comment by danielroe** [comment] 2020-02-07 09:01
The problem is your parser in your eslint config. You shouldn't use babel-eslint as it struggles with TypeScript.

**Comment by kevinmarrec** [comment] 2020-02-07 09:19
@rcheung9 

@danielroe is right, you need to remove https://github.com/rcheung9/ScanNuxt/blob/master/.eslintrc.js#L7

See the warning in `Lint` section of the documentation : https://typescript.nuxtjs.org/guide/lint.html#configuration

**Comment by kevinmarrec** [comment] 2020-02-07 09:20
@lukasborawski You may want to check your ESLint config if you don't have `babel-eslint` as well.

**Comment by rcheung9** [comment] 2020-02-07 09:23
@danielroe @kevinmarrec Thanks.  What do I need to change to get this formatting correct?

https://imgur.com/a/LzawGBr

This is from an existing vue-cli project.  I tried copying over the es-lint rules but it's still complaining.

**Comment by kevinmarrec** [comment] 2020-02-10 08:49
@rcheung9 First you can remove `@nuxtjs` cause `@nuxtjs/eslint-config-typescript` inherits from it.
Then it depends on what you need. On my projects I overall only use `@nuxtjs/eslint-config-typescript` (as I don't use `prettier`).

**Comment by rcheung9** [comment] 2020-02-12 06:06
@kevinmarrec I made a new project without prettier and it fixed a lot of issues.

I don't see any difference in the linting and formatting, not sure what the point of it was.  I see it being recommended to be used together with ESLint but it seems to cause more issues and has no benefits.

**Comment by kevinmarrec** [comment] 2020-02-14 10:24
@rcheung9 Cool ! Well I don't really have opinion on it, I just don't use it cause I'm fine without :)

@lukasborawski any update ?

**Comment by kevinmarrec** [comment] 2020-02-17 13:01
Closing as i'm pretty sure it's duplicate of https://github.com/nuxt/typescript/issues/136
Instructions about removing `eslint` are clear in https://typescript.nuxtjs.org/guide/lint.html

**Closed by kevinmarrec** 2020-02-17 13:01 UTC

**Comment by lukasborawski** [comment] 2020-02-17 21:07
I've made a workaround, it was also recommended in few places:

```
const menuProp: PropOptions<Menu> = {
  type: Array,
  required: true,
}

props: {
  menuProp,
},
```

Got the same type of issue with the data object, so the solution could look like that:

```
  data: (): Navigation => ({
    subnav: [],
  }),
```

and `Navigations` is a component interface. It works fine for me.
