### ISSUE TITLE
Nuxt + TypeScript not building with Firebase

### ISSUE THREAD

**Issue by Coooi** [nuxt/typescript#345] opened 2020-04-22 15:36 UTC
**Describe the bug**
I'm having issues when adding Firebase to my project.
Not sure it it's a bug from nuxt/typescript, but right after adding `yarn add firebase` the app won't build.

**To Reproduce**
1. Go to my TypeScript Nuxt project
2. `yarn add firebase`
3. `yarn dev`

I made this sample project that contains the same error: 
https://github.com/Coooi/nuxt-typescript-firebase-issue

**Expected behavior**
To build normally as without Firebase.

**Screenshots**
![image](https://user-images.githubusercontent.com/3846028/80002270-b6e06280-84bf-11ea-99d0-b58bb577da6e.png)

**Additional context**
Node 12
Nuxt 2.12.2
Firebase 7.14.1

**Dependencies:**

```
"dependencies": {
    "@nuxt/types": "^0.6.4",
    "@nuxt/typescript-runtime": "^0.4.0",
    "@nuxtjs/axios": "^5.9.5",
    "@nuxtjs/proxy": "^1.3.3",
    "@types/date-fns": "^2.6.0",
    "cross-env": "^5.2.0",
    "date-fns": "^2.11.0",
    "dotenv": "^8.2.0",
    "express": "^4.16.4",
    "firebase": "^7.14.1",
    "js-cookie": "^2.2.1",
    "lodash-es": "^4.17.15",
    "nuxt": "^2.0.0",
    "vue-ctk-date-time-picker": "^2.4.0",
    "vue-i18n": "^8.16.0",
    "vuex-persistedstate": "^3.0.0",
},
"devDependencies": {
    "@nuxt/typescript-build": "^0.6.0",
    "@nuxtjs/eslint-config-typescript": "^1.0.2",
    "@nuxtjs/style-resources": "^1.0.0",
    "@types/dotenv": "^8.2.0",
    "@types/lodash-es": "^4.17.3",
    "eslint": "^6.8.0",
    "node-sass": "^4.13.1",
    "nodemon": "^1.18.9",
    "sass-loader": "^8.0.2",
    "vue-class-component": "^7.2.3",
    "vue-property-decorator": "^8.4.1",
    "vuex-module-decorators": "^0.16.1"
  }
```

**Comment by kevinmarrec** [comment] 2020-04-22 16:01
@Coooi Removing `firebase` in the project you linked just works, so it seems `firebase` breaks the project indeed. They must have something wrong in their source code that cause the issue.

I think it's cause `firebase` uses an incompatible version of `core-js` within one of their dependencies, which interfers with `nuxt` one.

The issue is probably present even without typescript :/

**Comment by kevinmarrec** [comment] 2020-04-22 16:03
![image](https://user-images.githubusercontent.com/25272043/80005211-8b5f7700-84c3-11ea-8a38-841adb896f0f.png)

**Comment by kevinmarrec** [comment] 2020-04-22 16:06
Closing here, continue on main nuxt repo (https://github.com/nuxt/nuxt.js/issues/7258) cause it doesn't seem to be TS related

**Closed by kevinmarrec** 2020-04-22 16:06 UTC
