### ISSUE TITLE
Programmatic mode, Failed to show Nuxt.js app after 5 reloads

### ISSUE THREAD

**Issue by shalldie** [nuxt/typescript#152] opened 2019-10-16 11:39 UTC
**Describe the bug**

When i run nuxt in Programmatic mode, it shows error below:

![image](https://user-images.githubusercontent.com/9987486/66915662-232f6480-f04c-11e9-988a-55d2a8eb36e6.png)

**To Reproduce**
1. Clone repository https://github.com/shalldie/nuxt-programmatic-failed
2. Run  `npm i` & `npm run dev`
3. See error

**Expected behavior**
Nuxt works well.

**Additional context**

You can see detail step and how i fix it in a demo repository:

https://github.com/shalldie/nuxt-programmatic-failed

**Comment by shalldie** [comment] 2019-10-16 11:40
# nuxt-programmatic-failed

> SHOW ERROR

    Failed to show Nuxt.js app after 5 reloads

    Your Nuxt.js app could not be shown even though the webpack build appears to have finished.

    Try to reload the page manually, if this problem persists try to restart your Nuxt.js dev server.

## Step to show error

```bash
$ npm i

$ npm run dev
```

## How i fix this:

```bash

# 1. reset
$ rm -rf node_modules

$ rm package-lock.json

# 2. install nuxt first
$ npm i nuxt --save

# 3. install another two modules second
$ npm i @nuxt/typescript-build @nuxt/typescript-runtime --save

# 4. install other modules at last
$ npm i

# 5. it works!!
$ npm run dev

```

    So i think, the order of deps that matters!


The error repository branch:
https://github.com/shalldie/nuxt-programmatic-failed

The branch i fix it, you can find what are different in `package-lock.json`:
https://github.com/shalldie/nuxt-programmatic-failed/tree/order

**Comment by kevinmarrec** [comment] 2019-10-17 08:08
Hey, @shalldie Can you confirm it works with `yarn` over `npm` to install dependencies ?
See https://github.com/nuxt/typescript/issues/145#issuecomment-543009573

Most likely it's related and the issue is `npm` doing weird things when either installing or linking dependencies

**Comment by georgyfarniev** [comment] 2019-10-17 08:43
@kevinmarrec agreed that it probably related to npm. Confirming that it works with yarn. Also confirming that it's unrelated to lerna and programmatic usage of nuxt, it affects any cases where @nuxt/typescript-build are present in package.json under described circumstances.

**Comment by kevinmarrec** [comment] 2019-10-17 12:28
So `npm` + `@nuxt/typescript-build` = RIP

Hum, okay well I think we can ensure it's `npm` related so if @shalldie is alright we can close this issue as duplicated and change the other issue title

**Comment by georgyfarniev** [comment] 2019-10-17 12:31
@kevinmarrec yes, it’s irrelevant to usage mode or runtime. You can easily check my example repo in original issue, but I tried it many times with my colleague  while removing node_modules for sure.

**Comment by kevinmarrec** [comment] 2019-10-17 12:39
Duplicate of #145

**Comment by kevinmarrec** [comment] 2019-10-17 12:39
Duplicate of #145

**Closed by kevinmarrec** 2019-10-17 12:39 UTC
