### ISSUE TITLE
Could not use `optional chaining` in nuxt.config.ts

### ISSUE THREAD

**Issue by azawakh** [nuxt/typescript#248] opened 2019-12-11 03:39 UTC
**Describe the bug**
Using optional chaining in `nuxt.config.ts` causes run-time error.

```bash
 ERROR  Unexpected token . 

  const hello = fuga?.foo.bar;
  ^

  SyntaxError: Unexpected token .
```

**To Reproduce**
See CodeSandbox

https://codesandbox.io/embed/nuxtnuxtjs-typescript-q064y?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
No error happens

**Additional context**
To avoid this error, change `target` property's value of `tsconfig.json` into `es2018` from `esnext`.
https://github.com/TypeStrong/ts-node/issues/903#issuecomment-551265568

But the configuration displayed in the official document says that `targe` value is `esnext`.
https://typescript.nuxtjs.org/guide/setup.html#configuration

**Comment by kevinmarrec** [comment] 2019-12-11 08:49
@azawakh Wow thanks, it seems that babel plugins are not needed at all then, we can let TypeScript handles the transpilation of the features by specifying.

Only `esnext` seems buggy, `es5` / `es2018` / `es2019` / `es2020` work well.

I'm gonna remove Babel plugins and tell people to update their TypeScript configuration file in release so it works out of the box for `build` & `runtime` ouf of the box !

**Comment by kevinmarrec** [comment] 2019-12-11 09:58
I'm also gonna update Test fixture to use both new features in `runtime` & `build`, so the tests correctly check the features just correctly work :)

**Comment by kevinmarrec** [comment] 2019-12-11 14:13
Closed by https://github.com/nuxt/typescript/commit/826234b5ff24a90e771d10b1029d1adabd8de6fb

Babel plugins will be removed in next release later this day.

**Closed** 2019-12-11 14:14 UTC
Labels: bug, build, documentation, runtime

**Comment by husayt** [comment] 2019-12-11 14:56
That was what causing my issues as well it seems

**Comment by P4sca1** [comment] 2019-12-11 15:10
@kevinmarrec With this change optional chaining will only be possible in `<script lang="ts">` and no longer in `v-if statements` for example. We should add a note to the `README`.

**Comment by kevinmarrec** [comment] 2019-12-11 15:14
@P4sca1 Interesting, maybe it's worth keeping the babel plugins then and just tell people to use `es2018` for runtime

**Comment by P4sca1** [comment] 2019-12-11 15:45
Yes, also with `allowJs: true`. However, I think that not shipping the babel plugins by default and only allowing optional chaining and nullish coalescing in the script tag is the best approach.
Maybe we can introduce a config variable for setting up the babel plugins along with a hint in the docs saying that you have to manually install the babel plugins and enable that config variable.

**Comment by victorgarciaesgi** [comment] 2019-12-12 15:14
Still not working for me :(
 I've set `target: "es2018"`, but I still got errors on Vuex modules

![image](https://user-images.githubusercontent.com/15092120/70724059-341dee80-1cfa-11ea-8ce3-042350091336.png)

But I think it's from babel-loader because in the screeshot above, the code is purged from types so it passed the typescript compilation.

Even though I added `@babel/plugin-proposal-optional-chaining`, i still got errors

![image](https://user-images.githubusercontent.com/15092120/70724096-426c0a80-1cfa-11ea-93c6-acc6743544bc.png)

**Comment by kevinmarrec** [comment] 2019-12-12 16:04
What do you mean by `purged from types` ?
Are you able to give a repo with reproduction ?
Also your output show extra spaces between `?` & `.`

**Comment by victorgarciaesgi** [comment] 2019-12-12 16:44
I mean it's after the typescript build, in my code I have `(childId: string)`
I have no space in my code and no errors from vscode
Can't do reproducible case right now, i will try tomorrow!
