### ISSUE TITLE
Interface 'NuxtApp' incorrectly extends interface 'Vue' (typescript + Element-UI)

### ISSUE THREAD

**Issue by dclovec** [nuxt/typescript#354] opened 2020-04-21 01:59 UTC
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://jsbin.com/?html,output](https://jsbin.com/?html,output)

### Steps to reproduce

once I create a new nuxt.js project(typescript + Element-UI) and then run it, it's going wrong. Development and build are the same failure.

### What is expected ?

no failure found.

### What is actually happening?

nuxt:typescript 09:49:56rojects/test/node_modules/@nuxt/types/app/index.d.ts(119,18):
119:18 Interface 'NuxtApp' incorrectly extends interface 'Vue'.
  Types of property '$loading' are incompatible.
    Type 'NuxtLoading' is not assignable to type '(options: LoadingServiceOptions) => ElLoadingComponent'.
      Type 'DefaultNuxtLoading' is not assignable to type '(options: LoadingServiceOptions) => ElLoadingComponent'.
        Type 'DefaultNuxtLoading' provides no match for the signature '(options: LoadingServiceOptions): ElLoadingComponent'.

export interface NuxtApp extends Vue {
                             ^
$options: NuxtAppOptions
$loading: NuxtLoading
context: Context

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10545">#c10545</a>)</em></sub></div>

**Comment by kevinmarrec** [comment] 2020-05-06 13:54
Duplicate of #49 

See https://github.com/nuxt/typescript/issues/49#issuecomment-562945877

There's unfortunately nothing we can do, you may find workaround in the related issue.

From my POV it's not directly TypeScript issue but overall 2 frameworks setting a different `$loading` property on Vue instances. And as both are providing typings for it, it's buggy.

Overall I think it's component library fault (`element`, `buefy`, ...) cause they are 3rd parties, Nuxt isn't. Vuetify for example doesn't have this problem cause they namespaced everything in `$vuetify` object.

**Closed by kevinmarrec** 2020-05-06 13:54 UTC
